### ISSUE TITLE
Last editor is not updated ?

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#205]
After edit there is still pee@p.fi user who has edited a board..

I am Guest!

**Comment by narsuman** [comment]
![screenshot from 2015-07-21 14 30 23](https://cloud.githubusercontent.com/assets/8133582/8799775/6a0cd60a-2fb5-11e5-865a-b9ed51d7179e.png)

Im narsuman user, but still last editor is pee@pi.fi

**Comment by tanelih** [comment]
You can't have multiple login sessions in the same browser open... However this indicates that there are some de-sync issues with who the user is.

I think the issue here is that when the user logs in in a tab, and then in another does the same. Any API requests will get made with the token from the last created session, but the first session doesn't actually get any indication that the user was changed.

In a way, this is working as intended...

**Comment by narsuman** [comment]
There was users from different machines...

Guest name after edit should be visible anyway?

**Comment by narsuman** [comment]
Not working.. 

Client versio   v1.2.94
API versio  v0.4.35
IMG versio  v0.1.10

**Comment by narsuman** [comment]
New Implementation!

Closed now..
