### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by TommiHo** [N4SJAMK/teamboard-client-react#217]
There are few missing translations in contriboard. Here is one example
![image](https://cloud.githubusercontent.com/assets/12408338/8843907/8a5cce0c-3117-11e5-9ee1-4def081dfb03.png)

**Comment by narsuman** [comment]
![screenshot from 2015-07-23 10 17 16](https://cloud.githubusercontent.com/assets/8133582/8845047/fb5e3364-3123-11e5-9d45-49b91eba79b0.png)

Svenska också har en problem!

**Comment by TommiHo** [comment]
![image](https://cloud.githubusercontent.com/assets/12408338/8845249/f8bd9170-3125-11e5-968a-663e2ae75dee.png)

**Comment by TommiHo** [comment]
There are many missing translation in errors as well.

**Comment by nikolauska** [comment]
This is actually due to swedish, dansk and japan translation not being done. These will be fixed as soon as our translator has time do them. 

English and finnish should have all text translated.

**Comment by nikolauska** [comment]
This has been fixed in https://github.com/N4SJAMK/teamboard-client-react/commit/8633dc60afb75d8410fdeb7a2d6bdb9c07b0ca7d 

In production mode it will show english translations if it has not been translated to that specific language. In development mode it will still return translation ID to help find missing translations.

**Comment by narsuman** [comment]
Verified as fixed

Client versio   v1.2.118
API versio  v0.4.42
IMG versio  v0.1.10
