### ISSUE TITLE
Mystical white cross icon on the top black menu area ?

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#272]
![cross on top](https://cloud.githubusercontent.com/assets/8133582/8926247/0320e622-3517-11e5-96d2-7c4126958fcf.png)

When I try to create new ticket I will see white cross on black "menu" field

There will be plenty of thems... If I create more...

**Comment by narsuman** [comment]
Problem found from.. Ubuntu + Chrome

Client version  v1.2.112
API version v0.4.40
IMG version v0.1.10

**Comment by Temetz** [comment]
Sometimes this also happens when user logs out.

Need to take a look at `components/broadcaster.js`. Looks like in some cases the message content is empty that causes these empty error messages to be displayed.

![image](https://cloud.githubusercontent.com/assets/8721037/8926425/41e3bdb6-3518-11e5-9715-aa88e10d56a6.png)

**Comment by tanelih** [comment]
![](http://usercontent2.hubimg.com/8438671_f260.jpg)

**Comment by narsuman** [comment]
ready to verify ?
