### ISSUE TITLE
Logged user can enter board with any url 

### ISSUE THREAD

**Issue by F7347** [N4SJAMK/teamboard-client-react#56]
Product: Contriboard
Build Version: v1.2.3
Description: Logged user can enter to a boardview with an url like this: "http://lankku.n4sjamk.org/boards/AnythingYouWantToWrite" 
Reported By: Mikko Kemppinen

Steps:
1.Log in to Contriboard as an user
2.Enter "http://lankku.n4sjamk.org/boards/AnythingYouWantToWrite" as an Url. 
3.Press enter

Expected result: If the url is wrong, user is noticed that the board does NOT exist and user is taken back to workspace.

**Comment by tanelih** [comment]
We should probably create a `404` page, and on any requests that return the `404` we redirect to that page...

**Comment by melonmanchan** [comment]
Fixed in this commit: https://github.com/melonmanchan/teamboard-client-react/commit/dd7d206938f7fe5b67f52de3e907941a903228bd

We just send the user back to workspace if the board id is nonexistent. However the 404 is only returned if the boards/url could possibly be a valid MongoDB ObjectID. Otherwise the API automatically responds with 400 Bad Request. Currently the commit handles both cases by returning you to the workspace, which is fine IMO.

**Comment by tanelih** [comment]
Close this issue when the referenced commit gets merged here.
