### ISSUE TITLE
Ticket clipped out of board in board preview

### ISSUE THREAD

**Issue by narsuman** [N4SJAMK/teamboard-client-react#7]
_From @Monttinen on March 19, 2015 11:33_

peruna@peruna.org
pw: peruna123
http://student.labranet.jamk.fi/~G3318/testing/ClippedTicket.png

_Copied from original issue: N4SJAMK/teamboard-feedback#80_

**Comment by tanelih** [comment]
This is probably due to some `teamboard-api` shenanigans. There actually isn't a check whether or not the ticket is inside the bounds of the board, so if you POST a ticket directly there, not using the browser client, there is no check.

If this bug can be reproduced directly from `teamboard-client-react`, reopen this issue.

**Comment by narsuman** [comment]
Waiting for more incidents..
